name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy project to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_SSH_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        source: "."
        target: "/django-tests"

    - name: Build and run Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_SSH_PASSWORD }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd /django-tests
          docker-compose down
          docker-compose up --build -d
